# base image
FROM node:10.11.0-stretch

RUN apt-get install git
# set working directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add `/usr/src/app/node_modules/.bin` to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g react-scripts
RUN npm install -g @storybook/cli
RUN getstorybook

# start app
CMD ["npm", "start"]
