serve: docker-up

docker-up: docker-down docker-build
	docker-compose up --build

docker-down:
	docker-compose down

docker-build:
	docker-compose build

setup: docker-build

shell:
	docker exec -ti <%= @project_name %>-app bash
